services: # configuring each container
  db: # name of our mysql container
    image: mysql # default: latest; specify a version e.g. mysql:5.7
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    volumes: # data to map to the container
      - ./data:/docker-entrypoint-initdb.d # looks for sql file to use, can't be compressed apparently
    restart: always # always restart the container after reboot
    environment: # environment variables -- mysql options in this case
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
  wordpress: # name of our wordpress container
    env_file:
      - .env
    depends_on: # container dependencies that need to be running first
      - db
    image: wordpress:latest # image used by our container
    ports:
      - "8080:80" # setting our ports for networking # @TODO figure out a way to make this project url based project.test
    restart: always
    environment:
      WORDPRESS_DB_HOST: db # default mysql port
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress # matches the password set in the db container
      ## ignored if wp-config file is mapped below, make changes in wp-config-fsap.php instead
      # WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX}
      # WORDPRESS_DEBUG: 1
      # WORDPRESS_DEBUG_DISPLAY: 1
      # WORDPRESS_DEBUG_LOG: 1
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('WP_HOME', '${WP_HOME}');
      #   define('WP_SITEURL', '${WP_SITEURL}');
      #   define('WP_ENV', '${WP_ENV}');
      #   define('FS_METHOD', '${FS_METHOD}');
      #   define( 'WPS_DEBUG', true );
    volumes: # this is where we tell Docker what to pay attention to
      ## FSAP Default // if your repo is in another directory use SITE_PATH in the .env file e.g.: ./site/${SITE_PATH}/${SITE_THEME}:/var/www/html/..
      - ./site/${SITE_PATH}/wp-content/themes/${SITE_THEME}:/var/www/html/wp-content/themes/${SITE_THEME} # mapping our custom theme to the container
      - ./site/${SITE_PATH}/wp-content/plugins:/var/www/html/wp-content/plugins # map our plugins to the container, change the dir name as needed
      - ./site/wp-config-fsap.php:/var/www/html/wp-config.php # map to our wp-config file if we need more than the above ** NOTE: it will overrule what's determined above
      # - ./site/${SITE_THEME_PARENT}:/var/www/html/wp-content/themes/${SITE_THEME_PARENT} # mapping our custom parent theme to the container
      ## Options
      ## if you need to hold all of WP in the repo or it's just set up that way, comment out the above and uncomment below:
      #- ./site/${SITE_PATH}:/var/www/html
      ## keep uploads separated, depends on the usage
      # - ./data/uploads:/var/www/html/wp-content/uploads # map our uploads to the container

volumes: # persist the data for local dev
  data:
